### ISSUE TITLE
Fix Typings on DefinitelyTyped

### ISSUE THREAD

**Issue by MeirionHughes** [Level/community#104]
* [ ] encoding-down
  * default export no longer available
* [ ] leveldown:
  * default export no longer available
  * getMany()
* [ ] rocksdb: 
  * default export no longer available
  * getMany()
* [ ] levelup: 
  * default export no longer available
  * getMany()

**Comment by sebastianst** [comment]
The return type of `db.iterator()` also needs to be fixed. It should be something like `AsyncIterable<[K, V]>`. The current custom return type doesn't allow `for async (const x of it)` syntax in typescript code.

**Comment by sebastianst** [comment]
The `LevelUpConstructor` interface could be improved to accept a `ErrorValueCallback<LevelUp>` as the third parameter, it currently only receives `ErrorCallback`. (Or `ErrorValueCallback<LevelUp|undefined>`?)

**Comment by vweevers** [comment]
Relevant: https://github.com/Level/abstract-level/issues/5

**Comment by vweevers** [comment]
Closing because [`abstract-level`](https://github.com/Level/abstract-level) and dependents have built-in type declarations. If  someone wants to fix the typings of older modules on DT, go for it of course, but because @MeirionHughes is the main contributor of those types and seems to be busy, and the work needs to happen externally, I don't see an actionable item for us here.
