### ISSUE TITLE
Community page per repository. Add CoC, issue and PR templates?

### ISSUE THREAD

**Issue by ralphtheninja** [Level/community#32]
I had a quick glance of the community page for `level/level` and currently it looks as follows:

![screenshot from 2018-06-30 00-01-48](https://user-images.githubusercontent.com/308049/42116770-242dbe7c-7bf9-11e8-8d85-de747d103b42.png)

Should we have a Code of Conduct and templates for issues and PRs?

**Comment by vweevers** [comment]
Personally I feel like we're doing rather well as a community. If anyone (less privileged than a straight white male like me) feels otherwise - I welcome a CoC. Seeing as it isn't fair to expect those people to speak up, let's add a code of conduct anyway! To make our intentions clear (which I believe are good, but might not be visible), lower the barrier for contributors, etc.

**Comment by ralphtheninja** [comment]
I also feel we're doing well as a community. Just wanted to lift the issue for discussion.

**Comment by vweevers** [comment]
I like https://www.contributor-covenant.org/

**Comment by vweevers** [comment]
Added the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/) to the [default community health files](https://github.com/Level/.github/blob/master/CODE_OF_CONDUCT.md).

@Level/core If you have objections, speak now 😉
